from __future__ import annotations

from typing import Any, Protocol


class SimulationAdapter(Protocol):
    def initialize(self) -> None: ...
    def health_check(self) -> dict[str, Any]: ...
    def reset(self, seed: int, scenario: dict[str, Any]) -> None: ...
    def start(self) -> None: ...
    def submit_tasks(self, tasks: list[dict[str, Any]]) -> None: ...
    def observe(self) -> dict[str, Any]: ...
    def is_complete(self) -> bool: ...
    def has_failed(self) -> bool: ...
    def calculate_metrics(self) -> dict[str, float]: ...
    def export_replay(self, output_dir: str) -> None: ...
    def shutdown(self) -> None: ...

